name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: windows-latest
    environment: Azure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore Garagenparkmanager/Garagenparkmanager.sln

      - name: Build Server
        run: dotnet build -c Release --no-restore Garagenparkmanager/Garagenparkmanager.sln

      - name: Publish Server
        run: dotnet publish -c Release -o ./out Garagenparkmanager/Garagenparkmanager.sln

      - name: Build React app with Vite
        run: |
          cd garagenparkmanager.client
          npm install
          npm run build

      - name: Copy React build to wwwroot
        run: |
          xcopy /s /y garagenparkmanager.client/dist ./out/wwwroot

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: Garagenparkmanager-Webapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_GARAGENPARKMANAGER }}
          package: ./out
