name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore Garagenparkmanager/Garagenparkmanager.Server/Garagenparkmanager.Server.csproj

      - name: Build Server
        run: dotnet publish Garagenparkmanager/Garagenparkmanager.Server/Garagenparkmanager.Server.csproj -c Release -o ./out

      - name: Install Client Dependencies
        run: npm install
        working-directory: Garagenparkmanager/garagenparkmanager.client

      - name: Build Client
        run: npm run build
        working-directory: Garagenparkmanager/garagenparkmanager.client
        env:
          NODE_ENV: production

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: MyWeatherAPI
          publish-profile: ${{ secrets.AZURE_WEBAPP_GARAGENPARKMANAGER }}
          package: ./out      
