# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Garagenparkmanager-Webapp

on:
  push:
    branches:
      - main
env:
    DOTNET_VERSION: '8.0.x'
    
jobs:
  build:
    runs-on: windows-latest
    environment: Azure

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore dependencies
        run: dotnet restore Garagenparkmanager/Garagenparkmanager.sln

      - name: Build with dotnet
        run: dotnet build -c Release --no-restore Garagenparkmanager/Garagenparkmanager.sln

      - name: dotnet publish
        run: dotnet publish -c Release -o ./out/Garagenparkmanager/Garagenparkmanager.sln

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: Garagenparkmanager
          publish-profile: ${{ secrets.AZURE_WEBAPP_GARAGENPARKMANAGER }}
          package: ./out
