name: Build and deploy ASP.Net Core app to Azure Web App - Garagenparkmanager-Webapp

on:
  push:
    branches:
      - main
env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: windows-latest
    environment: Azure

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore Garagenparkmanager/Garagenparkmanager.Server/Garagenparkmanager.Server.csproj

      - name: Build with dotnet
        run: dotnet build Garagenparkmanager/Garagenparkmanager.Server/Garagenparkmanager.Server.csproj -c Release --no-restore

      - name: Publish Server
        run: dotnet publish Garagenparkmanager/Garagenparkmanager.Server/Garagenparkmanager.Server.csproj -c Release -o ./out

      - name: Install Client Dependencies
        run: npm install
        working-directory: Garagenparkmanager/garagenparkmanager.client

      - name: Build Client
        run: npm run build
        working-directory: Garagenparkmanager/garagenparkmanager.client
        env:
          NODE_ENV: production

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: Garagenparkmanager
          publish-profile: ${{ secrets.AZURE_WEBAPP_MYWHEATERFORECAST }}
          package: ./out
